name:        miso
version:     0.1.0.0
synopsis:    Personal notes with Hakyll
description: A personal "wiki" containing notes/summaries, built with Hakyll
category:    Web
github:      chuahou/miso
maintainer:  Chua Hou <human+github@chuahou.dev>

ghc-options:
    - -Wall
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-record-updates
    - -static
    - -threaded

default-extensions:
    - BangPatterns
    - DeriveGeneric
    - LambdaCase
    - QuasiQuotes
    - TupleSections
    - OverloadedStrings

dependencies:
    - base          >= 4.13 && < 5
    - bytestring   ^>= 0.10.10.1
    - filepath     ^>= 1.4.2.1
    - hakyll       ^>= 4.13.4.0
    - pandoc       ^>= 2.10.1
    - pandoc-types ^>= 1.21
    - text         ^>= 1.2.4.0
    - uri-encode   ^>= 1.5.0.6

executable:
    main: site.hs

extra-doc-files:
    - README.rst
