[input]
base_directory = "."
files = [
	{title = "miso", url = "https://chuahou.dev/miso/index.html", path = "docs/index.html"},
	{title = "Search", url = "https://chuahou.dev/miso/misc/search.html", path = "docs/misc/search.html"},
	{title = "University Summaries", url = "https://chuahou.dev/miso/uni/index.html", path = "docs/uni/index.html"},
	{title = "Lambda Calculus", url = "https://chuahou.dev/miso/uni/lc/index.html", path = "docs/uni/lc/index.html"},
	{title = "LC, Combinatory Logic", url = "https://chuahou.dev/miso/uni/lc/notes/combinatory.html", path = "docs/uni/lc/notes/combinatory.html"},
	{title = "LC, Computation", url = "https://chuahou.dev/miso/uni/lc/notes/computation.html", path = "docs/uni/lc/notes/computation.html"},
	{title = "LC, Normal Forms", url = "https://chuahou.dev/miso/uni/lc/notes/nf.html", path = "docs/uni/lc/notes/nf.html"},
	{title = "LC, Reduction Strategies", url = "https://chuahou.dev/miso/uni/lc/notes/redstrats.html", path = "docs/uni/lc/notes/redstrats.html"},
	{title = "LC, Reductions", url = "https://chuahou.dev/miso/uni/lc/notes/reductions.html", path = "docs/uni/lc/notes/reductions.html"},
	{title = "LC, Solvability", url = "https://chuahou.dev/miso/uni/lc/notes/solvability.html", path = "docs/uni/lc/notes/solvability.html"},
	{title = "LC, Syntax", url = "https://chuahou.dev/miso/uni/lc/notes/syntax.html", path = "docs/uni/lc/notes/syntax.html"},
	{title = "LC, Equational Theories", url = "https://chuahou.dev/miso/uni/lc/notes/theories.html", path = "docs/uni/lc/notes/theories.html"},
	{title = "LC, Simple Types", url = "https://chuahou.dev/miso/uni/lc/notes/types.html", path = "docs/uni/lc/notes/types.html"},
	{title = "LC, Principal Typing", url = "https://chuahou.dev/miso/uni/lc/notes/printyp.html", path = "docs/uni/lc/notes/printyp.html"},
]
