[input]
base_directory = "."
files = [
	{title = "404", url = "https://chuahou.dev/miso/404.html", path = "docs/404.html"},
	{title = "miso", url = "https://chuahou.dev/miso/index.html", path = "docs/index.html"},
	{title = "Random links and notes", url = "https://chuahou.dev/miso/misc/random.html", path = "docs/misc/random.html"},
	{title = "Search", url = "https://chuahou.dev/miso/misc/search.html", path = "docs/misc/search.html"},
	{title = "Recipes", url = "https://chuahou.dev/miso/recipes/index.html", path = "docs/recipes/index.html"},
	{title = "Peanut Soup", url = "https://chuahou.dev/miso/recipes/recipes/peanut_soup.html", path = "docs/recipes/recipes/peanut_soup.html"},
	{title = "Algorithms and Data Structures", url = "https://chuahou.dev/miso/uni/ads/index.html", path = "docs/uni/ads/index.html"},
	{title = "ADS, Amortized Analysis", url = "https://chuahou.dev/miso/uni/ads/notes/amortized.html", path = "docs/uni/ads/notes/amortized.html"},
	{title = "ADS, Approximation", url = "https://chuahou.dev/miso/uni/ads/notes/approx.html", path = "docs/uni/ads/notes/approx.html"},
	{title = "ADS, Red-Black Diagrams", url = "https://chuahou.dev/miso/uni/ads/notes/bst-rb-diag.html", path = "docs/uni/ads/notes/bst-rb-diag.html"},
	{title = "ADS, BSTs", url = "https://chuahou.dev/miso/uni/ads/notes/bst.html", path = "docs/uni/ads/notes/bst.html"},
	{title = "ADS, Flow Networks", url = "https://chuahou.dev/miso/uni/ads/notes/flownet.html", path = "docs/uni/ads/notes/flownet.html"},
	{title = "ADS, FPT", url = "https://chuahou.dev/miso/uni/ads/notes/fpt.html", path = "docs/uni/ads/notes/fpt.html"},
	{title = "ADS, Linear Programming", url = "https://chuahou.dev/miso/uni/ads/notes/lp.html", path = "docs/uni/ads/notes/lp.html"},
	{title = "ADS, Union-Find", url = "https://chuahou.dev/miso/uni/ads/notes/uf.html", path = "docs/uni/ads/notes/uf.html"},
	{title = "Concurrent Programming", url = "https://chuahou.dev/miso/uni/cp/index.html", path = "docs/uni/cp/index.html"},
	{title = "CP, Basics", url = "https://chuahou.dev/miso/uni/cp/notes/basics.html", path = "docs/uni/cp/notes/basics.html"},
	{title = "CP, Datatypes", url = "https://chuahou.dev/miso/uni/cp/notes/datatypes.html", path = "docs/uni/cp/notes/datatypes.html"},
	{title = "CP, Message Passing", url = "https://chuahou.dev/miso/uni/cp/notes/message.html", path = "docs/uni/cp/notes/message.html"},
	{title = "CP, Monitors", url = "https://chuahou.dev/miso/uni/cp/notes/monitors.html", path = "docs/uni/cp/notes/monitors.html"},
	{title = "CP, Design Patterns", url = "https://chuahou.dev/miso/uni/cp/notes/patterns.html", path = "docs/uni/cp/notes/patterns.html"},
	{title = "CP, Semaphores", url = "https://chuahou.dev/miso/uni/cp/notes/semaphores.html", path = "docs/uni/cp/notes/semaphores.html"},
	{title = "CP, Synchronization", url = "https://chuahou.dev/miso/uni/cp/notes/sync.html", path = "docs/uni/cp/notes/sync.html"},
	{title = "CP, Testing", url = "https://chuahou.dev/miso/uni/cp/notes/testing.html", path = "docs/uni/cp/notes/testing.html"},
	{title = "University Summaries", url = "https://chuahou.dev/miso/uni/index.html", path = "docs/uni/index.html"},
	{title = "Lambda Calculus", url = "https://chuahou.dev/miso/uni/lc/index.html", path = "docs/uni/lc/index.html"},
	{title = "LC, Combinatory Logic", url = "https://chuahou.dev/miso/uni/lc/notes/combinatory.html", path = "docs/uni/lc/notes/combinatory.html"},
	{title = "LC, Computation", url = "https://chuahou.dev/miso/uni/lc/notes/computation.html", path = "docs/uni/lc/notes/computation.html"},
	{title = "LC, Normal Forms", url = "https://chuahou.dev/miso/uni/lc/notes/nf.html", path = "docs/uni/lc/notes/nf.html"},
	{title = "LC, Principal Typing", url = "https://chuahou.dev/miso/uni/lc/notes/printyp.html", path = "docs/uni/lc/notes/printyp.html"},
	{title = "LC, Reduction Strategies", url = "https://chuahou.dev/miso/uni/lc/notes/redstrats.html", path = "docs/uni/lc/notes/redstrats.html"},
	{title = "LC, Reductions", url = "https://chuahou.dev/miso/uni/lc/notes/reductions.html", path = "docs/uni/lc/notes/reductions.html"},
	{title = "LC, Solvability", url = "https://chuahou.dev/miso/uni/lc/notes/solvability.html", path = "docs/uni/lc/notes/solvability.html"},
	{title = "LC, Syntax", url = "https://chuahou.dev/miso/uni/lc/notes/syntax.html", path = "docs/uni/lc/notes/syntax.html"},
	{title = "LC, Equational Theories", url = "https://chuahou.dev/miso/uni/lc/notes/theories.html", path = "docs/uni/lc/notes/theories.html"},
	{title = "LC, Simple Types", url = "https://chuahou.dev/miso/uni/lc/notes/types.html", path = "docs/uni/lc/notes/types.html"},
	{title = "Logic and Proof", url = "https://chuahou.dev/miso/uni/logic/index.html", path = "docs/uni/logic/index.html"},
	{title = "L&P, Normal Forms", url = "https://chuahou.dev/miso/uni/logic/notes/nf.html", path = "docs/uni/logic/notes/nf.html"},
	{title = "L&P, Propositional Logic", url = "https://chuahou.dev/miso/uni/logic/notes/prop.html", path = "docs/uni/logic/notes/prop.html"},
	{title = "Computer Networks", url = "https://chuahou.dev/miso/uni/networks/index.html", path = "docs/uni/networks/index.html"},
	{title = "Networks, Data Link Layer", url = "https://chuahou.dev/miso/uni/networks/notes/datalink.html", path = "docs/uni/networks/notes/datalink.html"},
	{title = "Networks, Metrics", url = "https://chuahou.dev/miso/uni/networks/notes/metrics.html", path = "docs/uni/networks/notes/metrics.html"},
	{title = "Networks, Physical Layer", url = "https://chuahou.dev/miso/uni/networks/notes/physical.html", path = "docs/uni/networks/notes/physical.html"},
	{title = "Concurrency", url = "https://chuahou.dev/miso/uni/ucs/index.html", path = "docs/uni/ucs/index.html"},
	{title = "UCS, Algebra Laws", url = "https://chuahou.dev/miso/uni/ucs/notes/algebra.html", path = "docs/uni/ucs/notes/algebra.html"},
	{title = "UCS, LTS Semantics", url = "https://chuahou.dev/miso/uni/ucs/notes/lts.html", path = "docs/uni/ucs/notes/lts.html"},
	{title = "UCS, Parallel Operators", url = "https://chuahou.dev/miso/uni/ucs/notes/parallel.html", path = "docs/uni/ucs/notes/parallel.html"},
	{title = "UCS, Sequential Process", url = "https://chuahou.dev/miso/uni/ucs/notes/seq.html", path = "docs/uni/ucs/notes/seq.html"},
	{title = "UCS, Traces Model", url = "https://chuahou.dev/miso/uni/ucs/notes/traces.html", path = "docs/uni/ucs/notes/traces.html"},
]
